version: "3.8"

networks:
  nt-666:
    driver: bridge
    name: nt-666

services:
  # Postgres database
  nest-task-management-database:
    image: postgres:12.2
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRE_DB_NAME}
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASS}
    ports:
      - '${POSTGRE_PORT}:5432'
    networks:
      - nt-666
    
  # Redis Services
  nest-task-management-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - nt-666